name= input("Enter your name:")
branch= input("Enter your branch:")
gender= input("Gender:")
colgname= input("Enter your college name:")
age= int(input("Age:"))
print("----------------------")
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College Name:",colgname)
print("Age:",age)
